// <auto-generated />
using System;
using AdvocateAssist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvocateAssist.Migrations
{
    [DbContext(typeof(AdvocateAssistContext))]
    [Migration("20250708190004_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvocateAssist.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientFname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientLname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NidNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferredBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            City = "Tongi",
                            ClientFname = "Mithila",
                            ClientLname = "Sultana",
                            DateOfBirth = new DateTime(1992, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Gazipur",
                            Division = "Dhaka",
                            Email = "mithila@example.com",
                            NidNumber = "1122334455",
                            PhoneNumber = "01811000001",
                            Picture = "mithila.png",
                            ReferredBy = "Mr. Rahman"
                        },
                        new
                        {
                            ClientId = 2,
                            City = "Teknaf",
                            ClientFname = "Abdullah",
                            ClientLname = "Khan",
                            DateOfBirth = new DateTime(1988, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Cox's Bazar",
                            Division = "Chittagong",
                            Email = "abdullah.k@example.com",
                            NidNumber = "556678899",
                            PhoneNumber = "01811000002",
                            Picture = "abdullah.jpg",
                            ReferredBy = "Self"
                        });
                });

            modelBuilder.Entity("AdvocateAssist.Entities.ClientPayment", b =>
                {
                    b.Property<int>("ClientPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientPaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientPaymentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentId");

                    b.ToTable("ClientPayments");

                    b.HasData(
                        new
                        {
                            ClientPaymentId = 1,
                            Amount = 1500.00m,
                            ClientId = 1,
                            PaymentDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 1,
                            ReceiptNumber = "RCPT-001",
                            Remarks = "Initial consultation",
                            TransactionNo = "TXN-001"
                        },
                        new
                        {
                            ClientPaymentId = 2,
                            Amount = 3000.00m,
                            ClientId = 2,
                            PaymentDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 2,
                            ReceiptNumber = "RCPT-002",
                            Remarks = "Filing fee for criminal case",
                            TransactionNo = "TXN-002"
                        });
                });

            modelBuilder.Entity("AdvocateAssist.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<string>("PaymentHead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            PaymentHead = "Consultation Fee"
                        },
                        new
                        {
                            PaymentId = 2,
                            PaymentHead = "Case Filing Fee"
                        },
                        new
                        {
                            PaymentId = 3,
                            PaymentHead = "Drafting Fee"
                        },
                        new
                        {
                            PaymentId = 4,
                            PaymentHead = "Incidental Cost "
                        });
                });

            modelBuilder.Entity("AdvocateAssist.Entities.ClientPayment", b =>
                {
                    b.HasOne("AdvocateAssist.Entities.Client", "Client")
                        .WithMany("ClientPayments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvocateAssist.Entities.Payment", "Payment")
                        .WithMany("ClientPayments")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AdvocateAssist.Entities.Client", b =>
                {
                    b.Navigation("ClientPayments");
                });

            modelBuilder.Entity("AdvocateAssist.Entities.Payment", b =>
                {
                    b.Navigation("ClientPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
